services:
  _defaults:
    public: true
    autowire: true

  huh.autocompletejs.manager.autocomplete_manager:
    class: HeimrichHannot\AutocompletejsBundle\Manager\AutocompleteManager
  HeimrichHannot\AutocompletejsBundle\Manager\AutocompleteManager: '@huh.autocompletejs.manager.autocomplete_manager'

  HeimrichHannot\AutocompletejsBundle\:
    resource: "../../{Asset,EventListener,Util}/*"
    autoconfigure: true